---
- name: Install missing packages.
  apk:
    name: ca-certificates
    state: present
- name: Create nginx config directories.
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - /etc/nginx
    - /etc/nginx/conf.d
    - "{{ favicon_dir }}"
- name: Install private key.
  copy:
    content: "{{ private_key }}"
    dest: "/etc/ssl/private/{{ key_name }}.key"
- name: Install cert.
  copy:
    content: "{{ cert }}"
    dest: "/etc/ssl/certs/{{ server_name }}.crt"
- name: Install ca-bundle.
  copy:
    content: "{{ ca }}"
    dest: "/etc/ssl/certs/{{ server_name }}.ca-bundle"
- name: Install nginx config.
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
- name: Install favicon.
  copy:
    src: favicon.ico
    dest: "{{ favicon_override }}"
- name: Template default conf.
  template:
    src: default.j2
    dest: /etc/nginx/conf.d/default.conf
...
